# Generated by Django 4.2.16 on 2025-09-30 19:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import people.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_code', models.CharField(default=people.models.generate_person_code, help_text='Unique person code (auto-generated)', max_length=20, unique=True)),
                ('given_name', models.CharField(help_text='First name', max_length=100)),
                ('family_name', models.CharField(help_text='Last name', max_length=100)),
                ('preferred_name', models.CharField(blank=True, help_text='Nickname or preferred name', max_length=100)),
                ('date_of_birth', models.DateField(help_text='Date of birth')),
                ('email', models.EmailField(blank=True, help_text='Email address (unique if provided)', max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Primary phone number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('phone_secondary', models.CharField(blank=True, help_text='Secondary phone number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address_line1', models.CharField(help_text='Street address', max_length=255)),
                ('address_line2', models.CharField(blank=True, help_text='Apartment, suite, unit, etc.', max_length=255)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state', models.CharField(help_text='State/Province', max_length=50)),
                ('postal_code', models.CharField(help_text='Postal/ZIP code', max_length=20)),
                ('country', models.CharField(default='Australia', help_text='Country', max_length=100)),
                ('emergency_contact_name', models.CharField(blank=True, help_text='Emergency contact name', max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, help_text='Emergency contact phone', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('notes', models.TextField(blank=True, help_text='General notes about this person')),
                ('is_active', models.BooleanField(default=True, help_text='Is this person active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='User account for portal access (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': ['family_name', 'given_name'],
                'indexes': [models.Index(fields=['person_code'], name='people_pers_person__7ba29f_idx'), models.Index(fields=['email'], name='people_pers_email_52ffb2_idx'), models.Index(fields=['family_name', 'given_name'], name='people_pers_family__1e8bce_idx'), models.Index(fields=['is_active'], name='people_pers_is_acti_c9fc80_idx')],
            },
        ),
    ]
