# Generated by Django 4.2.16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_person_user'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='person',
            field=models.OneToOneField(blank=True, help_text='Link to Person record if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='people.person'),
        ),
    ]
