# Generated by Django 4.2.24 on 2025-10-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('staff', 'Staff Member'), ('teacher', 'Teacher'), ('parent', 'Parent/Guardian'), ('guardian', 'Guardian'), ('student', 'Student')], default='staff', help_text="User's role in the system", max_length=20),
        ),
    ]
