name: Security Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 0 * * MON'  # Weekly security scan

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd backend
        pip install -r requirements.txt
        pip install safety bandit

    - name: Run Safety check
      continue-on-error: true
      run: |
        cd backend
        safety check

    - name: Run Bandit security linter
      continue-on-error: true
      run: |
        cd backend
        bandit -r . -f json -o bandit-report.json

    - name: Run npm audit
      continue-on-error: true
      run: |
        cd frontend
        npm audit